// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
/// The request as the host hands it over. `path` is the part AFTER the
/// route prefix (always starts with "/"); `query` is the raw query string
/// (may be ""); the host caps `body` at 10 MiB before invoking.
#[derive(Clone)]
pub struct HttpRequest {
    pub method: _rt::String,
    pub path: _rt::String,
    pub query: _rt::String,
    pub headers: _rt::Vec<(_rt::String, _rt::String)>,
    pub body: _rt::Vec<u8>,
}
impl ::core::fmt::Debug for HttpRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("HttpRequest")
            .field("method", &self.method)
            .field("path", &self.path)
            .field("query", &self.query)
            .field("headers", &self.headers)
            .field("body", &self.body)
            .finish()
    }
}
#[derive(Clone)]
pub struct HttpResponse {
    pub status: u16,
    pub headers: _rt::Vec<(_rt::String, _rt::String)>,
    pub body: _rt::Vec<u8>,
}
impl ::core::fmt::Debug for HttpResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("HttpResponse")
            .field("status", &self.status)
            .field("headers", &self.headers)
            .field("body", &self.body)
            .finish()
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_handle_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
    arg4: *mut u8,
    arg5: usize,
    arg6: *mut u8,
    arg7: usize,
    arg8: *mut u8,
    arg9: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg3;
    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
    let len2 = arg5;
    let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
    let base9 = arg6;
    let len9 = arg7;
    let mut result9 = _rt::Vec::with_capacity(len9);
    for i in 0..len9 {
        let base = base9.add(i * (4 * ::core::mem::size_of::<*const u8>()));
        let e9 = {
            let l3 = *base.add(0).cast::<*mut u8>();
            let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len5 = l4;
            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
            let l6 = *base
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l7 = *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len8 = l7;
            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
            (_rt::string_lift(bytes5), _rt::string_lift(bytes8))
        };
        result9.push(e9);
    }
    _rt::cabi_dealloc(
        base9,
        len9 * (4 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let len10 = arg9;
    let result11 = T::handle(HttpRequest {
        method: _rt::string_lift(bytes0),
        path: _rt::string_lift(bytes1),
        query: _rt::string_lift(bytes2),
        headers: result9,
        body: _rt::Vec::from_raw_parts(arg8.cast(), len10, len10),
    });
    let ptr12 = (&raw mut _RET_AREA.0).cast::<u8>();
    let HttpResponse { status: status13, headers: headers13, body: body13 } = result11;
    *ptr12.add(0).cast::<u16>() = (_rt::as_i32(status13)) as u16;
    let vec17 = headers13;
    let len17 = vec17.len();
    let layout17 = _rt::alloc::Layout::from_size_align_unchecked(
        vec17.len() * (4 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result17 = if layout17.size() != 0 {
        let ptr = _rt::alloc::alloc(layout17).cast::<u8>();
        if ptr.is_null() {
            _rt::alloc::handle_alloc_error(layout17);
        }
        ptr
    } else {
        ::core::ptr::null_mut()
    };
    for (i, e) in vec17.into_iter().enumerate() {
        let base = result17.add(i * (4 * ::core::mem::size_of::<*const u8>()));
        {
            let (t14_0, t14_1) = e;
            let vec15 = (t14_0.into_bytes()).into_boxed_slice();
            let ptr15 = vec15.as_ptr().cast::<u8>();
            let len15 = vec15.len();
            ::core::mem::forget(vec15);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
            *base.add(0).cast::<*mut u8>() = ptr15.cast_mut();
            let vec16 = (t14_1.into_bytes()).into_boxed_slice();
            let ptr16 = vec16.as_ptr().cast::<u8>();
            let len16 = vec16.len();
            ::core::mem::forget(vec16);
            *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len16;
            *base.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr16
                .cast_mut();
        }
    }
    *ptr12.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len17;
    *ptr12.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result17;
    let vec18 = (body13).into_boxed_slice();
    let ptr18 = vec18.as_ptr().cast::<u8>();
    let len18 = vec18.len();
    ::core::mem::forget(vec18);
    *ptr12.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len18;
    *ptr12.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr18
        .cast_mut();
    ptr12
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_handle<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l1 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base6 = l0;
    let len6 = l1;
    for i in 0..len6 {
        let base = base6.add(i * (4 * ::core::mem::size_of::<*const u8>()));
        {
            let l2 = *base.add(0).cast::<*mut u8>();
            let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l2, l3, 1);
            let l4 = *base
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l5 = *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l4, l5, 1);
        }
    }
    _rt::cabi_dealloc(
        base6,
        len6 * (4 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let l7 = *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l8 = *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base9 = l7;
    let len9 = l8;
    _rt::cabi_dealloc(base9, len9 * 1, 1);
}
pub trait Guest {
    fn handle(req: HttpRequest) -> HttpResponse;
}
#[doc(hidden)]
macro_rules! __export_world_handler_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "handle")] unsafe extern "C" fn
        export_handle(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4
        : * mut u8, arg5 : usize, arg6 : * mut u8, arg7 : usize, arg8 : * mut u8, arg9 :
        usize,) -> * mut u8 { unsafe { $($path_to_types)*:: _export_handle_cabi::<$ty >
        (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) } } #[unsafe
        (export_name = "cabi_post_handle")] unsafe extern "C" fn _post_return_handle(arg0
        : * mut u8,) { unsafe { $($path_to_types)*:: __post_return_handle::<$ty > (arg0)
        } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_handler_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 5 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 5 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod keel {
    pub mod workflow {
        /// Phase 4 (micro-cloud) — the FUNCTION host surface. Everything here is
        /// DIRECT, not journaled: functions are stateless and non-durable on purpose
        /// (no journal, no replay, real now/random). Durability lives one door over —
        /// a function that needs reliability calls start-workflow.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod platform_api {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            /// Forwarded to engine logs with a `fn:` prefix. Not metered.
            pub fn log(msg: &str) -> () {
                unsafe {
                    let vec0 = msg;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "keel:workflow/platform-api@0.7.0")]
                    unsafe extern "C" {
                        #[link_name = "log"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Real wall clock, unix epoch milliseconds. Direct (functions replay never).
            pub fn now_ms() -> u64 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "keel:workflow/platform-api@0.7.0")]
                    unsafe extern "C" {
                        #[link_name = "now-ms"]
                        fn wit_import0() -> i64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    ret as u64
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Real randomness. Direct.
            pub fn random_u64() -> u64 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "keel:workflow/platform-api@0.7.0")]
                    unsafe extern "C" {
                        #[link_name = "random-u64"]
                        fn wit_import0() -> i64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    ret as u64
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Start a durable workflow (base-spec semantics: the row commits before
            /// the spawn). Returns the workflow id; err = unknown module hash.
            pub fn start_workflow(
                module_hash: &str,
                input: &str,
            ) -> Result<_rt::String, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = module_hash;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = input;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "keel:workflow/platform-api@0.7.0")]
                    unsafe extern "C" {
                        #[link_name = "start-workflow"]
                        fn wit_import3(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2)
                    };
                    let l4 = i32::from(*ptr2.add(0).cast::<u8>());
                    let result11 = match l4 {
                        0 => {
                            let e = {
                                let l5 = *ptr2
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l6 = *ptr2
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len7 = l6;
                                let bytes7 = _rt::Vec::from_raw_parts(
                                    l5.cast(),
                                    len7,
                                    len7,
                                );
                                _rt::string_lift(bytes7)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l8 = *ptr2
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l9 = *ptr2
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len10 = l9;
                                let bytes10 = _rt::Vec::from_raw_parts(
                                    l8.cast(),
                                    len10,
                                    len10,
                                );
                                _rt::string_lift(bytes10)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result11
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Fetch a workflow as a JSON string — the same shape as
            /// GET /api/workflows/:id ({"id","status","output",...}). err = unknown id.
            pub fn get_workflow(id: &str) -> Result<_rt::String, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = id;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "keel:workflow/platform-api@0.7.0")]
                    unsafe extern "C" {
                        #[link_name = "get-workflow"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result10 = match l3 {
                        0 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                let bytes6 = _rt::Vec::from_raw_parts(
                                    l4.cast(),
                                    len6,
                                    len6,
                                );
                                _rt::string_lift(bytes6)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l7 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l8 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len9 = l8;
                                let bytes9 = _rt::Vec::from_raw_parts(
                                    l7.cast(),
                                    len9,
                                    len9,
                                );
                                _rt::string_lift(bytes9)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result10
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_handler_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_handler_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_handler_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:keel:workflow@0.7.0:handler:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 463] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd1\x02\x01A\x02\x01\
A\x0b\x01o\x02ss\x01p\0\x01p}\x01r\x05\x06methods\x04paths\x05querys\x07headers\x01\
\x04body\x02\x03\0\x0chttp-request\x03\0\x03\x01r\x03\x06status{\x07headers\x01\x04\
body\x02\x03\0\x0dhttp-response\x03\0\x05\x01B\x0a\x01@\x01\x03msgs\x01\0\x04\0\x03\
log\x01\0\x01@\0\0w\x04\0\x06now-ms\x01\x01\x04\0\x0arandom-u64\x01\x01\x01j\x01\
s\x01s\x01@\x02\x0bmodule-hashs\x05inputs\0\x02\x04\0\x0estart-workflow\x01\x03\x01\
@\x01\x02ids\0\x02\x04\0\x0cget-workflow\x01\x04\x03\0\x20keel:workflow/platform\
-api@0.7.0\x05\x07\x01@\x01\x03req\x04\0\x06\x04\0\x06handle\x01\x08\x04\0\x1bke\
el:workflow/handler@0.7.0\x04\0\x0b\x0d\x01\0\x07handler\x03\0\0\0G\x09producers\
\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41\
.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
