// echo-fn — phase 4 acceptance function (see Cargo.toml header).
//
// Functions are NOT durable and NOT deterministic (ext spec §E1): this one
// needs neither property — it just reflects what the dispatcher handed it,
// which is exactly what accept_phase4.sh asserts on.
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::{HttpRequest, HttpResponse};

struct Component;

impl bindings::Guest for Component {
    fn handle(req: HttpRequest) -> HttpResponse {
        let body = serde_json::json!({
            "method": req.method,
            "path": req.path,
            "query": req.query,
            "body_len": req.body.len(),
        })
        .to_string();
        HttpResponse {
            status: 200,
            headers: vec![
                ("content-type".to_string(), "application/json".to_string()),
                ("x-echo-method".to_string(), req.method.clone()),
            ],
            body: body.into_bytes(),
        }
    }
}

bindings::export!(Component with_types_in bindings);
