// starter-fn — phase 4 acceptance function AND the phase-6 app backend (see
// Cargo.toml header). The Lambda-calls-Step-Functions merger in ~80 lines:
//
//   POST /start  {"module_hash": "...", "input": {...}}  → 202 {"workflow_id"}
//   GET  /status?id=<workflow-id>                        → 200 (workflow JSON)
//   anything else                                        → 404
//
// The function itself is stateless; durability lives in the workflow it
// starts. Relative paths only — the same component serves /fn/jobs and
// /apps/<name>/api without knowing which.
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::platform_api;
use bindings::{HttpRequest, HttpResponse};

struct Component;

fn json_response(status: u16, body: serde_json::Value) -> HttpResponse {
    HttpResponse {
        status,
        headers: vec![("content-type".to_string(), "application/json".to_string())],
        body: body.to_string().into_bytes(),
    }
}

/// The one query shape we need: extract `id` from "a=b&id=c&...".
fn query_id(query: &str) -> Option<String> {
    query
        .split('&')
        .find_map(|kv| kv.strip_prefix("id="))
        .map(|s| s.to_string())
}

impl bindings::Guest for Component {
    fn handle(req: HttpRequest) -> HttpResponse {
        match (req.method.as_str(), req.path.as_str()) {
            ("POST", "/start") => {
                let parsed: serde_json::Value = match serde_json::from_slice(&req.body) {
                    Ok(v) => v,
                    Err(e) => {
                        return json_response(
                            400,
                            serde_json::json!({"error": format!("bad JSON body: {e}")}),
                        )
                    }
                };
                let Some(hash) = parsed.get("module_hash").and_then(|v| v.as_str()) else {
                    return json_response(
                        400,
                        serde_json::json!({"error": "missing field: module_hash"}),
                    );
                };
                let input = parsed
                    .get("input")
                    .cloned()
                    .unwrap_or(serde_json::json!({}));
                match platform_api::start_workflow(hash, &input.to_string()) {
                    Ok(id) => {
                        platform_api::log(&format!("started workflow {id}"));
                        json_response(202, serde_json::json!({"workflow_id": id}))
                    }
                    Err(e) => json_response(500, serde_json::json!({"error": e})),
                }
            }
            ("GET", "/status") => {
                let Some(id) = query_id(&req.query) else {
                    return json_response(
                        400,
                        serde_json::json!({"error": "missing query param: id"}),
                    );
                };
                match platform_api::get_workflow(&id) {
                    // Relay the engine's JSON verbatim (same shape as
                    // GET /api/workflows/:id — that equality is the bridge
                    // proof in accept_phase4.sh).
                    Ok(json) => HttpResponse {
                        status: 200,
                        headers: vec![(
                            "content-type".to_string(),
                            "application/json".to_string(),
                        )],
                        body: json.into_bytes(),
                    },
                    Err(e) => json_response(404, serde_json::json!({"error": e})),
                }
            }
            _ => json_response(404, serde_json::json!({"error": "not found"})),
        }
    }
}

bindings::export!(Component with_types_in bindings);
