// demo guest — phase 1 acceptance guest (SPEC.md Task 1.6).
//
// GUEST RULES (apply to every guest): no std::time, no std::thread::sleep, no
// println!, no rand — on wasm32-unknown-unknown those either panic or are silently
// useless. Use host::* instead. That restriction is a feature: it is what makes the
// guest deterministic (and therefore replayable).
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;

struct Component;

impl bindings::Guest for Component {
    fn run(input: String) -> Result<String, String> {
        host::log(&format!("starting with input {input}"));
        let stamp = host::random_u64();
        let a = host::http_get("https://example.com/")?;
        host::log(&format!("first fetch: {} bytes", a.len()));
        host::sleep_ms(15_000);
        let b = host::http_get("https://example.com/")?;
        Ok(format!(
            r#"{{"stamp":{stamp},"first_len":{},"second_len":{}}}"#,
            a.len(),
            b.len()
        ))
    }
}

bindings::export!(Component with_types_in bindings);
