// demo guest — phase 1 acceptance guest (SPEC.md Task 1.6).
//
// GUEST RULES (apply to every guest): no std::time, no std::thread::sleep, no
// println!, no rand — on wasm32-unknown-unknown those either panic or are silently
// useless. Use host::* instead. That restriction is a feature: it is what makes the
// guest deterministic (and therefore replayable).
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;

struct Component;

impl bindings::Guest for Component {
    fn run(input: String) -> Result<String, String> {
        host::log(&format!("starting with input {input}"));
        // Post-review hardening: the fetch target comes from input ({"url": ...})
        // so the acceptance script can point it at a local stub — the definition
        // of done must not depend on example.com/DNS being reachable. Determinism
        // is unaffected: input is fixed at creation, so replay derives the same
        // url. The default keeps bare {} runs working.
        let url = serde_json::from_str::<serde_json::Value>(&input)
            .ok()
            .and_then(|v| v.get("url").and_then(|u| u.as_str()).map(str::to_string))
            .unwrap_or_else(|| "https://example.com/".to_string());
        let stamp = host::random_u64();
        let a = host::http_get(&url)?;
        host::log(&format!("first fetch: {} bytes", a.len()));
        host::sleep_ms(15_000);
        let b = host::http_get(&url)?;
        Ok(format!(
            r#"{{"stamp":{stamp},"first_len":{},"second_len":{}}}"#,
            a.len(),
            b.len()
        ))
    }

    // WIT 0.3.0 (Task 3.1): resume is a REQUIRED export. This guest never calls
    // checkpoint, so the engine can never legitimately invoke this — the spec's
    // prescribed stub.
    fn resume(_state: Vec<u8>) -> Result<String, String> {
        Err("no checkpoints".to_string())
    }
}

bindings::export!(Component with_types_in bindings);
