// relay guest — v2.5 acceptance guest (see Cargo.toml header).
//
// Sequence: provider-call(relay, relay, {first_url, second_url, body}) → 5s
// durable sleep → done. smoke_providers_effectful.sh drives two flavors:
//   * kill -9 while the provider is mid-SECOND-post: recovery re-invokes the
//     provider, the FIRST post replays from its own journal row (never
//     re-fired), the second re-sends with the SAME idempotency key.
//   * kill -9 in the sleep AFTER the call completed: recovery fast-forwards
//     the whole recorded provider scope without instantiating the provider.
//
// GUEST RULES (apply to every guest): no std::time, no std::thread::sleep, no
// println!, no rand — use host::* instead (see guests/demo).
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;

struct Component;

impl bindings::Guest for Component {
    fn run(input: String) -> Result<String, String> {
        let v: serde_json::Value =
            serde_json::from_str(&input).map_err(|e| format!("bad input: {e}"))?;
        let get = |k: &str| -> String {
            v.get(k)
                .and_then(|x| x.as_str())
                .unwrap_or_default()
                .to_string()
        };
        let req = serde_json::json!({
            "first_url": get("first_url"),
            "second_url": get("second_url"),
            "body": "from-relay-guest",
        });
        let out = host::provider_call("relay", "relay", &req.to_string())?;

        host::sleep_ms(5_000); // the post-completion crash window

        Ok(serde_json::json!({ "relay": out }).to_string())
    }

    fn resume(_state: Vec<u8>) -> Result<String, String> {
        Err("relay guest never checkpoints".to_string())
    }
}

bindings::export!(Component with_types_in bindings);
