// loadgen guest — v2.4 load-test guest (see Cargo.toml header). One http-get,
// no sleeps: the permit is held only for the fetch, so load_test.sh measures
// the engine's concurrency machinery, not a guest's nap schedule.
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;

struct Component;

impl bindings::Guest for Component {
    fn run(input: String) -> Result<String, String> {
        let url = serde_json::from_str::<serde_json::Value>(&input)
            .ok()
            .and_then(|v| v.get("url").and_then(|u| u.as_str()).map(str::to_string))
            .ok_or_else(|| r#"input must be {"url": "http://host:port/path"}"#.to_string())?;
        let body = host::http_get(&url)?;
        Ok(format!(r#"{{"len":{}}}"#, body.len()))
    }

    fn resume(_state: Vec<u8>) -> Result<String, String> {
        Err("no checkpoints".to_string())
    }
}

bindings::export!(Component with_types_in bindings);
