// approval guest — phase 2 acceptance guest (SPEC.md Task 2.9).
//
// Exercises both phase-2 park points: block on an external "approve" event, then
// a durable 60s sleep, then finish with the event's payload embedded in the
// output. The phase-2 acceptance script kill -9s the engine once at each park.
//
// GUEST RULES (apply to every guest): no std::time, no std::thread::sleep, no
// println!, no rand — use host::* instead (see guests/demo).
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;

struct Component;

impl bindings::Guest for Component {
    fn run(input: String) -> Result<String, String> {
        host::log(&format!("starting with input {input}; waiting for approval"));
        // Parks (status waiting_event) until POST .../events {"name":"approve",...};
        // d is the event's payload JSON text, journaled — identical on replay.
        let d = host::await_event("approve");
        host::log(&format!("approved with {d}; settling for 60s"));
        host::sleep_ms(60_000);
        // d is already JSON — embed it raw, don't re-quote it.
        Ok(format!(r#"{{"approved_with":{d}}}"#))
    }
}

bindings::export!(Component with_types_in bindings);
