// counter guest — phase 3 acceptance guest (SPEC.md Task 3.7). One crate, two
// artifacts: the default build is v1, `--features v2` is v2. The acceptance
// script uploads both and live-upgrades a running v1 workflow to v2.
//
// Both entry points funnel into the same tick loop. The checkpoint after every
// tick is what makes the journal prune — and what makes the upgrade possible:
// the state blob fully determines all FUTURE host calls (SPEC.md Task 3.1
// contract), so the engine can restart the guest from it under new code.
//
// v1 state: {"count": u32, "target": u32}
// v2 state: {"total": u32, "target": u32, "note": String}; v2's parse_state
// migrates a v1-shaped blob (count → total, note = "upgraded") — exactly what a
// mid-flight upgrade hands it.
//
// GUEST RULES (apply to every guest): no std::time, no std::thread::sleep, no
// println!, no rand — use host::* instead (see guests/demo).
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;
use serde::{Deserialize, Serialize};

struct Component;

#[derive(Deserialize)]
struct Input {
    target: u32,
}

impl bindings::Guest for Component {
    fn run(input: String) -> Result<String, String> {
        let inp: Input = serde_json::from_str(&input)
            .map_err(|e| format!(r#"input must be {{"target": <u32>}}: {e}"#))?;
        host::log(&format!("counter starting toward {}", inp.target));
        tick_loop(init_state(inp.target))
    }

    fn resume(state: Vec<u8>) -> Result<String, String> {
        let s = parse_state(&state)?;
        host::log("counter resuming from checkpoint");
        tick_loop(s)
    }
}

// --- v1 ------------------------------------------------------------------------

#[cfg(not(feature = "v2"))]
#[derive(Serialize, Deserialize)]
struct State {
    count: u32,
    target: u32,
}

#[cfg(not(feature = "v2"))]
fn init_state(target: u32) -> State {
    State { count: 0, target }
}

#[cfg(not(feature = "v2"))]
fn parse_state(bytes: &[u8]) -> Result<State, String> {
    serde_json::from_slice(bytes).map_err(|e| format!("bad v1 state: {e}"))
}

#[cfg(not(feature = "v2"))]
fn tick_loop(mut s: State) -> Result<String, String> {
    while s.count < s.target {
        host::sleep_ms(5_000);
        s.count += 1;
        let bytes = serde_json::to_vec(&s).map_err(|e| e.to_string())?;
        host::checkpoint(&bytes);
        host::log(&format!("v1 tick {}/{}", s.count, s.target));
    }
    Ok(serde_json::json!({ "count": s.count }).to_string())
}

// --- v2 ------------------------------------------------------------------------

#[cfg(feature = "v2")]
#[derive(Serialize, Deserialize)]
struct State {
    total: u32,
    target: u32,
    note: String,
}

#[cfg(feature = "v2")]
fn init_state(target: u32) -> State {
    State {
        total: 0,
        target,
        note: String::new(),
    }
}

#[cfg(feature = "v2")]
fn parse_state(bytes: &[u8]) -> Result<State, String> {
    // v2 shape first (has total+note); on failure it must be a pre-upgrade v1
    // blob — migrate it (SPEC.md Task 3.7).
    #[derive(Deserialize)]
    struct V1 {
        count: u32,
        target: u32,
    }
    if let Ok(s) = serde_json::from_slice::<State>(bytes) {
        return Ok(s);
    }
    let v1: V1 =
        serde_json::from_slice(bytes).map_err(|e| format!("state is neither v2 nor v1: {e}"))?;
    Ok(State {
        total: v1.count,
        target: v1.target,
        note: "upgraded".to_string(),
    })
}

#[cfg(feature = "v2")]
fn tick_loop(mut s: State) -> Result<String, String> {
    while s.total < s.target {
        host::sleep_ms(5_000);
        s.total += 1;
        let bytes = serde_json::to_vec(&s).map_err(|e| e.to_string())?;
        host::checkpoint(&bytes);
        host::log(&format!("v2 tick {}/{}", s.total, s.target));
    }
    Ok(serde_json::json!({ "total": s.total, "note": s.note }).to_string())
}

bindings::export!(Component with_types_in bindings);
