// providerdemo guest — v2.2 acceptance guest (see Cargo.toml header).
//
// Sequence: provider-call(greet, greet) → 5s durable sleep (the crash
// window) → provider-call(greet, shout) → provider-call(nope, x) which must
// err as DATA. After a kill -9 in the sleep, recovery replays the first
// provider call from the journal — smoke_providers.sh proves the provider
// itself ran exactly once by counting the engine's "invoking provider" line.
//
// GUEST RULES (apply to every guest): no std::time, no std::thread::sleep, no
// println!, no rand — use host::* instead (see guests/demo).
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;

struct Component;

impl bindings::Guest for Component {
    fn run(_input: String) -> Result<String, String> {
        let a = host::provider_call(
            "greet",
            "greet",
            &serde_json::json!({ "name": "keel" }).to_string(),
        )?;

        host::sleep_ms(5_000); // smoke_providers.sh kill -9s the engine here

        let b = host::provider_call("greet", "shout", "\"hi\"")?;
        let missing = host::provider_call("nope", "x", "{}");

        Ok(serde_json::json!({
            "a": a,
            "b": b,
            "missing_err": missing.is_err(),
        })
        .to_string())
    }

    fn resume(_state: Vec<u8>) -> Result<String, String> {
        Err("no checkpoints".to_string())
    }
}

bindings::export!(Component with_types_in bindings);
