// secrets guest — v2.1 acceptance guest (see Cargo.toml header).
//
// Sequence: secret("stub-token") → POST /echo with the value in an
// authorization header → 6s durable sleep (the crash window) → secret again.
// Recovery replays the seq-0 secret read (hash check against the LIVE file)
// and the POST (the stub's counter must not move); the post-sleep secret read
// runs live at a fresh seq and must return the same value. smoke_secrets.sh
// also rotates the file under a second workflow parked in the same sleep —
// that recovery must fail the workflow loudly, not resume it.
//
// GUEST RULES (apply to every guest): no std::time, no std::thread::sleep, no
// println!, no rand — use host::* instead (see guests/demo).
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;

struct Component;

impl bindings::Guest for Component {
    fn run(input: String) -> Result<String, String> {
        let base = serde_json::from_str::<serde_json::Value>(&input)
            .ok()
            .and_then(|v| v.get("base").and_then(|b| b.as_str()).map(str::to_string))
            .ok_or_else(|| r#"input must be {"base": "http://host:port"}"#.to_string())?;

        let token = host::secret("stub-token")?;
        let resp = host::http_request(
            "POST",
            &format!("{base}/echo"),
            &[("authorization".to_string(), format!("Bearer {token}"))],
            Some("secret smoke"),
            0,
            0,
        )?;

        host::sleep_ms(6_000); // smoke_secrets.sh kill -9s the engine here

        let again = host::secret("stub-token")?;
        Ok(serde_json::json!({
            "status": resp.status,
            "stable": again == token,
        })
        .to_string())
    }

    fn resume(_state: Vec<u8>) -> Result<String, String> {
        Err("no checkpoints".to_string())
    }
}

bindings::export!(Component with_types_in bindings);
