// spin guest — the cancel-me fixture (post-review hardening; smoke_cancel.sh).
//
// It logs once and then spins in PURE WASM forever: no host calls, no parks.
// That makes it uncancellable by the park-loop abort flag — the only thing that
// can stop it is the engine's epoch-deadline callback (runner.rs), which traps
// aborted guests at the next 1s epoch tick. This guest exists so that path has
// a regression test.
//
// GUEST RULES (apply to every guest): no std::time, no std::thread::sleep, no
// println!, no rand — use host::* instead (see guests/demo).
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;

struct Component;

impl bindings::Guest for Component {
    fn run(_input: String) -> Result<String, String> {
        host::log("spinning forever in pure wasm — cancel me");
        #[allow(clippy::empty_loop)]
        loop {}
    }

    fn resume(_state: Vec<u8>) -> Result<String, String> {
        Err("no checkpoints".to_string())
    }
}

bindings::export!(Component with_types_in bindings);
