// relay — the sample EFFECTFUL capability provider (see Cargo.toml header).
//
// Unlike pure providers, this world imports keel:provider/host-http: each
// http_request below is a REAL wire call, journaled at its own seq inside the
// calling workflow's journal. The engine replays committed calls from the
// journal on a crash re-run, so this code must be deterministic given
// (kind, request, import responses) — same rule as guests.
//
// src/bindings.rs is GENERATED by `cargo component build` from
// ../../provider-wit — never edit it by hand.

#[allow(warnings)]
mod bindings;

use bindings::keel::provider::host_http;

struct Component;

fn post(url: &str, body: &str) -> Result<u16, String> {
    let resp = host_http::http_request("POST", url, &[], Some(body), 0, 0)?;
    Ok(resp.status)
}

impl bindings::Guest for Component {
    fn handle(kind: String, request: String) -> Result<String, String> {
        match kind.as_str() {
            "relay" => {
                let v: serde_json::Value = serde_json::from_str(&request)
                    .map_err(|e| format!("relay wants JSON: {e}"))?;
                let get = |k: &str| -> Result<String, String> {
                    v.get(k)
                        .and_then(|x| x.as_str())
                        .map(str::to_string)
                        .ok_or_else(|| format!(r#"relay wants {{"{k}": "..."}}"#))
                };
                let (first, second) = (get("first_url")?, get("second_url")?);
                let body = get("body").unwrap_or_default();
                let s1 = post(&first, &body)?;
                let s2 = post(&second, &body)?;
                Ok(serde_json::json!({ "first_status": s1, "second_status": s2 }).to_string())
            }
            other => Err(format!("unknown kind '{other}'")),
        }
    }
}

bindings::export!(Component with_types_in bindings);
