// kvup guest (v1) — v2.3 acceptance guest (see Cargo.toml header).
//
// Sequence: kv-set k=below → checkpoint (C) → kv-set k=above → park on
// await-event("go"). smoke_kv_upgrade.sh upgrades the parked workflow to
// kvup2; the tail-discard drops the k=above version (seq > C) and kvup2's
// resume() must read k=below. If the operator instead sends "go" with no
// upgrade, run() completes reporting k=above (the sanity path).
//
// GUEST RULES (apply to every guest): no std::time, no std::thread::sleep, no
// println!, no rand — use host::* instead (see guests/demo).
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;

struct Component;

fn tail_after_checkpoint() -> Result<String, String> {
    host::kv_set("k", "above");
    let _ = host::await_event("go");
    let k = host::kv_get("k").unwrap_or_default();
    Ok(serde_json::json!({ "path": "v1", "k": k }).to_string())
}

impl bindings::Guest for Component {
    fn run(_input: String) -> Result<String, String> {
        host::kv_set("k", "below");
        host::checkpoint(b"kvup-v1");
        tail_after_checkpoint()
    }

    fn resume(_state: Vec<u8>) -> Result<String, String> {
        // Same future host calls as run()'s post-checkpoint tail — the
        // checkpoint contract (a crash-recovery under v1 replays through
        // here; the interesting path is the UPGRADE to kvup2 instead).
        tail_after_checkpoint()
    }
}

bindings::export!(Component with_types_in bindings);
