// greet — the sample capability provider (see Cargo.toml header).
//
// A provider is request→response and NOTHING else: no clocks, no sockets, no
// host-api (the world imports nothing, and the engine's pre-flight refuses
// components that try). Unknown kinds are Err — the calling guest sees that
// as data, exactly like an http transport error.
//
// src/bindings.rs is GENERATED by `cargo component build` from
// ../../provider-wit — never edit it by hand.

#[allow(warnings)]
mod bindings;

struct Component;

impl bindings::Guest for Component {
    fn handle(kind: String, request: String) -> Result<String, String> {
        match kind.as_str() {
            "greet" => {
                let name = serde_json::from_str::<serde_json::Value>(&request)
                    .ok()
                    .and_then(|v| v.get("name").and_then(|n| n.as_str()).map(str::to_string))
                    .ok_or_else(|| r#"greet wants {"name": "..."}"#.to_string())?;
                Ok(serde_json::json!({ "greeting": format!("hello {name}") }).to_string())
            }
            "shout" => Ok(request.to_uppercase()),
            other => Err(format!("unknown kind '{other}'")),
        }
    }
}

bindings::export!(Component with_types_in bindings);
