// kvup2 guest (v2) — v2.3 acceptance guest (see Cargo.toml header).
//
// resume() reads kv FIRST and reports what it sees. Arriving here via
// upgrade-from-kvup, the tail-discard has dropped kvup's post-checkpoint
// k=above version — this read must see k=below. That single assertion is
// what closed the old "kv survives the discarded tail" caveat.
//
// src/bindings.rs is GENERATED by `cargo component build` from ../../wit — never
// edit it by hand; it regenerates when the wit changes.

#[allow(warnings)]
mod bindings;

use bindings::keel::workflow::host_api as host;

struct Component;

impl bindings::Guest for Component {
    fn run(_input: String) -> Result<String, String> {
        Err("kvup2 is the upgrade target — start kvup (v1) instead".to_string())
    }

    fn resume(_state: Vec<u8>) -> Result<String, String> {
        let k = host::kv_get("k").unwrap_or_default();
        Ok(serde_json::json!({ "path": "v2-resume", "k": k }).to_string())
    }
}

bindings::export!(Component with_types_in bindings);
